app:
  port: 5000
  jwt_secret: helloworld

db:
  database: hotel-reservation
  uri: mongodb://localhost:27017

test_db:
  database: hotel-reservation-test
  uri: mongodb://localhost:27017

